version: '3'
services:
  api:
    build: docker/php
    depends_on:
      - database
    links:
      - "database:database"
  database:
    build: docker/database
    environment:
     - ORACLE_ALLOW_REMOTE=true
     - ORACLE_DISABLE_ASYNCH_IO=true
    ports:
      - 49161:1521